### ISSUE TITLE
Plans? 

### ISSUE THREAD

**Issue by mpariente** [Reckless564/Conv-TasNet#1]
Hi, 

I just saw you created this repo. Can I ask what are the plans for it? 

I'd love if you would contribute to [asteroid](https://github.com/mpariente/AsSteroid), feel free ! :-)

**Comment by Reckless564** [comment]
Of course , I'm willing to contribute the asteroid. 
But I have a exam this weekend, so I will update it next week.
And  I also find a similar project: [Onseen](https://github.com/speechLabBcCuny/onssen) ,maybe you could refer to that.

**Comment by mpariente** [comment]
Thanks for the reference on Onseen, I've seen it as well. We might integrate some things together.
